version: 2

jobs:
  build:
    working_directory: ~/clj-cctray

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-clj-cctray-{{ checksum "project.clj" }}

      - run:
          name: install
          command: ./lein.sh deps

      - save_cache:
          key: v1-clj-cctray-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - run:
          name: lint
          command: ./lein.sh lint

      - run:
          name: test
          when: always
          command: ./lein.sh coverage

      - store_test_results:
          path: ./target/coverage-reports

      - store_artifacts:
          path: ./target/coverage-reports

  release:
    working_directory: ~/clj-cctray

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-clj-cctray-{{ checksum "project.clj" }}

      - run:
          name: create release on GitHub
          command: |
            ./lein.sh jar
            ./.circleci/release-github.sh

      - run:
          name: update the docs
          command: ./.circleci/release-docs.sh

      # do this last as the other jobs can be easily reverted if this errors
      - run:
          name: create release on Clojars
          command: ./lein.sh deploy releases

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - release:
          requires:
            - hold
