version: 2

jobs:
  build:
    branches:
      ignore:
        - gh-pages

    working_directory: ~/clj-cctray

    docker:
      - image: circleci/openjdk:8-jdk

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-clj-cctray-{{ checksum "project.clj" }}

      - run:
          name: build
          command: ./ci/compile.sh

      - save_cache:
          key: v1-clj-cctray-{{ checksum "project.clj" }}
          paths:
            - ~/.m2

      - run:
          name: test
          command: ./ci/test.sh

      - run:
          name: move jar to different folder
          command: |
            mkdir ./target/clj-cctray-jar
            mv ./target/*.jar ./target/jar/

      - store_test_results:
          path: ./target/surefire-reports

      - store_artifacts:
          path: ./target/jar

      - persist_to_workspace:
          root: .
          paths:
            - ./resources/*.xml
            - ./ci/*
            - ./target/jar/*.jar

  release:
    working_directory: ~/clj-cctray

    docker:
    - image: circleci/openjdk:8-jdk

    steps:
    - attach_workspace:
        at: ~/clj-cctray

    - run:
        name: export version
        command: ./ci/export-version.sh

    - run:
        name: move jar back to target
        command: mv target/jar/*.jar target/

    - run:
        name: create release on GitHub
        command: ./ci/release-github.sh

    - run:
        name: create release on Clojars
        command: ./ci/release-clojars.sh

workflows:
  version: 2
  build-deploy:
    jobs:
    - build
    - hold:
        type: approval
        requires:
          - build
    - release:
        requires:
          - hold
